[tool.poetry]
name = "language-gandalf"
version = "0.1.0"
description = ""
authors = ["Simran Awadia <simran.awadia@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
g4f = "^0.0.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
